package com.insigniait.accessControl.dto;

public class AddFaceRecordCondition {
	
	/**
	 * Picture storage URL inputted when uploading the face picture by URL, the maximum length is 256 bytes
	 */
	private String faceURL;
	
	/**
	 * Face picture library type: "blackFD"-list library, "staticFD"-static library, string type, the maximum size is 32 bytes
	 */
	private String faceLibType;
	
	/**
	 * Face picture library ID, the maximum size is 63 bytes
	 */
	private String FDID;
	
	/**
	 * Face record ID, it can be generated by device or inputted. If it is inputted, 
	 * it should be the unique ID with the combination of letters and digits, 
	 * and the maximum length is 63 bytes; 
	 * if it is generated by the device automatically, it is the same as the employee No. (person ID)
	 */
	private String FPID;
	
	/**
	 * Name of person in the face picture, string type, the maximum size is 96 bytes
	 */
	private String name;

	/**
	 *  Gender of person in the face picture: male, female, unknown
	 */
	private String gender;
	
	/**
	 * Birthday of person in the face picture, ISO8601 time format
	 */
	private String bornTime;
	
	/**
	 * City code of birth for the person in the face picture
	 */
	private String city;
	
	/**
	 * Certificate type: "officerID"-officer ID, "ID"-identify card, passport, other
	 */
	private String certificateType;
	
	/**
	 * Certificate No., string, the max. size is 32 bytes
	 */
	private String certificateNumber;
	
	/**
	 * Case information, the max. size is 192 bytes, it is valid when faceLibType is "blackFD"
	 */
	private String caseInfo;
	
	/**
	 * Custom tag, up to 4 tags, which are separated by commas
	 * the max. size is 195 bytes, it is valid when faceLibType is "blackFD"
	 */
	private String tag;
	
	/**
	 * Person address, it is valid when faceLibType is "staticFD"
	 */
	private String address;
	
	/**
	 * Custom information, the max. size is 192 bytes, it is valid when faceLibType is "staticFD"
	 */
	private String customInfo;
	
	/**
	 *  Target model data, non-modeled binary data needs to be encrypted by Base64 during transmission
	 */
	private String modelData;
	
	/**
	 * Whether to enable transfer
	 */
	private Boolean transfer;

	public String getFaceURL() {
		return faceURL;
	}

	public void setFaceURL(String faceURL) {
		this.faceURL = faceURL;
	}

	public String getFaceLibType() {
		return faceLibType;
	}

	public void setFaceLibType(String faceLibType) {
		this.faceLibType = faceLibType;
	}

	public String getFDID() {
		return FDID;
	}

	public void setFDID(String FDID) {
		this.FDID = FDID;
	}

	public String getFPID() {
		return FPID;
	}

	public void setFPID(String FPID) {
		this.FPID = FPID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getBornTime() {
		return bornTime;
	}

	public void setBornTime(String bornTime) {
		this.bornTime = bornTime;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCertificateType() {
		return certificateType;
	}

	public void setCertificateType(String certificateType) {
		this.certificateType = certificateType;
	}

	public String getCertificateNumber() {
		return certificateNumber;
	}

	public void setCertificateNumber(String certificateNumber) {
		this.certificateNumber = certificateNumber;
	}

	public String getCaseInfo() {
		return caseInfo;
	}

	public void setCaseInfo(String caseInfo) {
		this.caseInfo = caseInfo;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCustomInfo() {
		return customInfo;
	}

	public void setCustomInfo(String customInfo) {
		this.customInfo = customInfo;
	}

	public String getModelData() {
		return modelData;
	}

	public void setModelData(String modelData) {
		this.modelData = modelData;
	}

	public Boolean getTransfer() {
		return transfer;
	}

	public void setTransfer(Boolean transfer) {
		this.transfer = transfer;
	}
	
}
